"""
Summary builder — produces run_summary.md from run state.
"""
from __future__ import annotations

import textwrap
from typing import Any, Dict, List, Optional


def build_summary(state: Dict[str, Any]) -> str:
    run_id       = state.get("run_id", "unknown")
    generated_at = state.get("generated_at", "")
    qs           = state.get("queue_state", {})
    tasks        = state.get("tasks", [])
    lineage      = state.get("lineage", {})

    total    = qs.get("total",    0)
    done     = qs.get("done",     0)
    failed   = qs.get("failed",   0)
    canceled = qs.get("canceled", 0)
    workers  = qs.get("workers",  0)
    paused   = qs.get("paused",   False)

    outcome = "SUCCESS" if failed == 0 and canceled == 0 else "PARTIAL" if done > 0 else "FAILED"

    lines: List[str] = [
        f"# Mission Control Run Report",
        f"",
        f"**Run ID:** `{run_id}`  ",
        f"**Generated:** {generated_at}  ",
        f"**Outcome:** {outcome}  ",
        f"",
        f"---",
        f"",
        f"## Queue Summary",
        f"",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Workers | {workers} |",
        f"| Total Tasks | {total} |",
        f"| Done | {done} |",
        f"| Failed | {failed} |",
        f"| Canceled | {canceled} |",
        f"| Paused | {'Yes' if paused else 'No'} |",
        f"",
    ]

    if tasks:
        lines += [
            f"## Task Execution",
            f"",
            f"| Task ID | Agent | Status | Attempts | Provider |",
            f"|---------|-------|--------|----------|----------|",
        ]
        for t in tasks:
            tid      = t.get("task_id", "?")[:16]
            agent    = t.get("agent_name") or "—"
            status   = t.get("status", "?")
            attempts = t.get("attempts", 0)
            ar       = t.get("agent_result") or {}
            provider = ar.get("provider") or "—"
            failover = ar.get("failover_from")
            if failover:
                provider = f"{provider} (failover from {failover})"
            lines.append(f"| `{tid}` | {agent} | {status} | {attempts} | {provider} |")
        lines.append("")

    if lineage and lineage.get("ok"):
        root   = lineage.get("task_id", "?")
        parent = lineage.get("parent_task_id")
        kids   = lineage.get("child_task_ids") or []
        lines += [
            f"## Lineage",
            f"",
            f"- Root task: `{root}`",
        ]
        if parent:
            lines.append(f"- Parent: `{parent}`")
        if kids:
            lines.append(f"- Children: {len(kids)}")
            for k in kids:
                lines.append(f"  - `{k}`")
        lines.append("")

    agent_outputs = state.get("agent_outputs", {})
    if agent_outputs:
        lines += ["## Agent Outputs", ""]
        for agent_name, output in agent_outputs.items():
            lines.append(f"### {agent_name}")
            lines.append("")
            if isinstance(output, dict):
                for k, v in output.items():
                    if isinstance(v, str) and "\n" in v:
                        lines.append(f"**{k}:**")
                        lines.append("```")
                        lines.append(v[:500] + ("..." if len(v) > 500 else ""))
                        lines.append("```")
                    else:
                        lines.append(f"- **{k}:** {v}")
            else:
                lines.append(str(output))
            lines.append("")

    lines += [
        "---",
        "",
        "_Generated by Mission Control Run Report Layer_",
    ]

    return "\n".join(lines)
