import { buildEvidence, confidenceBucket, isoDate, nowIso } from './utils.js'

export function createCanonicalCandidate(input = {}) {
  return {
    ticker: input.ticker || '',
    companyName: input.companyName || input.company_name || '',
    sector: input.sector || '',
    industry: input.industry || '',
    quoteType: input.quoteType || '',
    exchange: input.exchange || '',
    fullExchangeName: input.fullExchangeName || '',
    marketState: input.marketState || '',
    tradeable: input.tradeable ?? true,
    otcLike: Boolean(input.otcLike ?? input.otc_flag),
    otc_flag: Boolean(input.otc_flag ?? input.otcLike),
    sharesOutstanding: input.sharesOutstanding ?? null,
    currentPrice: input.currentPrice ?? null,
    annualRevenue: input.annualRevenue ?? null,
    eps: input.eps ?? null,
    netIncome: input.netIncome ?? null,
    cashFlow: input.cashFlow ?? null,
    balanceSheetRisk: input.balanceSheetRisk ?? null,
    dilutionRisk: input.dilutionRisk ?? null,
    verificationStatus: input.verificationStatus || 'unverified',
    verificationNotes: input.verificationNotes || '',
    healthStatus: input.healthStatus || 'unknown',
    watchlistRank: input.watchlistRank ?? null,
    watchlistScore: input.watchlistScore ?? null,
    price: input.price ?? null,
    volume: input.volume ?? null,
    averageVolume: input.averageVolume ?? null,
    relativeVolume: input.relativeVolume ?? null,
    dailyMovePct: input.dailyMovePct ?? null,
    marketMomentumPct: input.marketMomentumPct ?? null,
    longMomentumPct: input.longMomentumPct ?? null,
    liquidityMetric: input.liquidityMetric ?? null,
    catalystNewsPresence: Boolean(input.catalystNewsPresence),
    initialScannerNotes: input.initialScannerNotes || '',
    timestamp: input.timestamp || nowIso(),
    sourceMeta: input.sourceMeta || {},
    sources: input.sources || [],
    validationSources: input.validationSources || {},
    evidence: input.evidence || {},
    dataCompleteness: input.dataCompleteness ?? 0,
    dataQuality: input.dataQuality || 'Low',
    source_count: input.source_count ?? input.sourceCount ?? 0,
    sourceCount: input.sourceCount ?? input.source_count ?? 0,
    data_confidence: input.data_confidence ?? input.dataConfidence ?? 0,
    dataConfidence: input.dataConfidence ?? input.data_confidence ?? 0,
    missing_fields: input.missing_fields || input.missingFields || [],
    missingFields: input.missingFields || input.missing_fields || [],
    validation_status: input.validation_status || input.validationStatus || 'unverified',
    validationStatus: input.validationStatus || input.validation_status || 'unverified',
    validation_flags: input.validation_flags || input.validationFlags || [],
    validationFlags: input.validationFlags || input.validation_flags || [],
    validation_issues: input.validation_issues || input.validationIssues || [],
    validationIssues: input.validationIssues || input.validation_issues || [],
    verification_status: input.verification_status || 'UNVERIFIED',
    verificationStatus: input.verificationStatus || input.verification_status || 'UNVERIFIED',
    rejection_reasons: input.rejection_reasons || input.rejectionReasons || [],
    rejectionReasons: input.rejectionReasons || input.rejection_reasons || [],
    confidence_score: input.confidence_score ?? input.confidenceScore ?? 0,
    confidenceScore: input.confidenceScore ?? input.confidence_score ?? 0,
    source_agreement: input.source_agreement || input.sourceAgreement || 'FAIL',
    sourceAgreement: input.sourceAgreement || input.source_agreement || 'FAIL',
    critical_field_check: input.critical_field_check || input.criticalFieldCheck || 'FAIL',
    criticalFieldCheck: input.criticalFieldCheck || input.critical_field_check || 'FAIL',
    verification: input.verification || null,
    marketCap: input.marketCap ?? null,
    low52w: input.low52w ?? null,
    high52w: input.high52w ?? null,
    marketSignals: input.marketSignals || {},
    overview: input.overview || {},
    financials: input.financials || {},
    news: input.news || [],
    filings: input.filings || [],
    riskSignals: input.riskSignals || {},
    scannerStatus: input.scannerStatus || 'unknown',
    scannerReasons: input.scannerReasons || [],
    scorecard: input.scorecard || null,
    analysis: input.analysis || null,
    normalizedAt: input.normalizedAt || null,
    researchMeta: input.researchMeta || {},
  }
}

export function createFieldEvidence(value, source, note = '', confidence = 1) {
  return buildEvidence(value, source, note, confidence)
}

export function buildCandidateSummary(candidate) {
  return {
    ticker: candidate.ticker,
    companyName: candidate.companyName,
    sector: candidate.sector,
    price: candidate.price,
    relativeVolume: candidate.relativeVolume,
    dailyMovePct: candidate.dailyMovePct,
    catalystNewsPresence: candidate.catalystNewsPresence,
    confidenceLevel: confidenceBucket(candidate.dataCompleteness),
    timestamp: candidate.timestamp,
  }
}

export function createReportContext({ candidate, scorecard, analysis, scenario, capital, executive, pricing, rollup, run }) {
  return {
    analysisDate: isoDate(),
    run,
    candidate,
    scorecard,
    analysis,
    scenario,
    capital,
    executive,
    pricing,
    rollup,
    confidenceLevel: candidate?.dataQuality || 'Low',
    recommendation: scorecard?.recommendation || 'PASS',
    rating: scorecard?.finalRating || 'Pass',
    createdAt: nowIso(),
  }
}
