import fs from 'fs'
import path from 'path'
import { EXPECTED_MORNING_JOBS } from './runtimePurge.js'
const HOLD_IDS=['healthcare-teams-zoho-message-logging-middleware','internal-speculative-middleware']
const HOLD_TITLES=['Healthcare Teams-to-Zoho Message Logging Middleware','Internal Speculative Middleware']
const j=(f,d=null)=>{try{return fs.existsSync(f)?JSON.parse(fs.readFileSync(f,'utf8')):d}catch{return d}}
const w=(f,v)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,JSON.stringify(v,null,2));return f}
export const ensureOperationalRecoveryRoots=root=>{for(const p of ['runtime/executor-evidence','runtime/project-holds','runtime/report-execution-timeline','runtime/cooldown-fallback'])fs.mkdirSync(path.join(root,p),{recursive:true})}
export const executorEvidencePath=root=>path.join(root,'runtime','executor-evidence','latest-executor-evidence.json')
export const holdRegistryPath=root=>path.join(root,'runtime','project-holds','hold-registry.json')
export const cooldownFallbackPath=root=>path.join(root,'runtime','cooldown-fallback','latest.json')
export const reportTimelinePath=root=>path.join(root,'runtime','report-execution-timeline','timeline.jsonl')
export function appendExecutorEvidence(root,entry={}){ensureOperationalRecoveryRoots(root);const f=executorEvidencePath(root);const d=j(f,{updatedAt:null,tasks:[]});d.updatedAt=new Date().toISOString();d.tasks=[{...entry,timestamp:entry.timestamp||new Date().toISOString()},...(d.tasks||[])].slice(0,200);w(f,d);return d}
export const loadExecutorEvidence=root=>j(executorEvidencePath(root),{updatedAt:null,tasks:[]})
export function buildRoutingPolicy(){return{localModelsAvailable:false,currentPrimaryExecutor:'codex',gptUsageMode:'review-escalation',localFirstEnabled:true,localEligibleTaskTypes:['grep/search audits','file inventory','stale/static data detection','report formatting','docs/protocol drafts','simple tests','non-destructive endpoint scaffolding','jsx cleanup with tests','scheduled report artifact indexing','blog formatting/drafting','ci summary generation'],gptOnlyTaskTypes:['architecture decisions','security-sensitive edits','destructive cleanup','production deployment decisions','credential/billing/legal/client-facing actions','final validation','ambiguous high-risk refactors'],recentFallbackReasons:[],tokenConservationMode:true}}
export function buildLocalHealth(){const exists=fs.existsSync('/usr/local/bin/ollama')||fs.existsSync('/usr/bin/ollama');return{qwenAvailable:false,qwenModelName:null,lastQwenTestAt:new Date().toISOString(),lastQwenTestStatus:exists?'failed':'unavailable',localExecutorCommand:exists?'ollama run qwen2.5-coder:7b-instruct':'ollama unavailable',localExecutorFailureReason:exists?'could not connect to ollama server, run `ollama serve` to start it':'ollama binary unavailable',fallbackReady:false,tokenConservationMode:true}}
export const writeCooldownFallback=(root,p={})=>w(cooldownFallbackPath(root),{gptAvailable:!p.cooldownDetected,cooldownDetected:Boolean(p.cooldownDetected),fallbackExecutor:p.fallbackExecutor||'local_ollama',allowedWorkDuringCooldown:p.allowedWorkDuringCooldown||['report formatting','blog drafting','artifact indexing','audits','docs','queue/report status generation'],pausedWorkDuringCooldown:p.pausedWorkDuringCooldown||['high-stakes finance judgment','new strategy decisions','client-facing final approval','production deployment decisions'],lastFallbackRun:new Date().toISOString()})
export const loadCooldownFallback=root=>j(cooldownFallbackPath(root),{gptAvailable:true,cooldownDetected:false,fallbackExecutor:'local_ollama',allowedWorkDuringCooldown:[],pausedWorkDuringCooldown:[],lastFallbackRun:null})
export function buildHoldRegistry(root){ensureOperationalRecoveryRoots(root);const f=holdRegistryPath(root);const existing=j(f,{projects:[]});if(existing.projects?.length)return existing;const projects=[{id:HOLD_IDS[0],title:HOLD_TITLES[0],owner:'Icky',holdReason:'Permanent hold until client reactivation',holdDate:new Date().toISOString(),restartConditions:['client reactivation','explicit Patrick approval'],artifactLocations:['/home/patrick/projects/internal-tools/healthcare-teams-zoho-middleware'],preservedRoutes:[],preservedSchemas:['docs/zoho-communications-schema-draft.md'],preservedReports:[],preservedDependencies:[],resumeNotes:'Preserve architecture and notes; no active execution.'},{id:HOLD_IDS[1],title:HOLD_TITLES[1],owner:'Icky',holdReason:'Speculative middleware initiatives paused pending ROI/necessity/demand proof',holdDate:new Date().toISOString(),restartConditions:['measurable ROI','operational necessity','validated market demand'],artifactLocations:['/home/patrick/mission-control/governance/middleware-hub-wedge-checklist.md','/home/patrick/mission-control/reports/middleware-hub-architecture-decision-2026-04-26.md'],preservedRoutes:[],preservedSchemas:[],preservedReports:['reports/middleware-hub-architecture-decision-2026-04-26.md'],preservedDependencies:[],resumeNotes:'Do not auto-resume or inflate runtime queues.'}];return j(w(f,{updatedAt:new Date().toISOString(),projects}),{updatedAt:null,projects})}
export function classifyHoldMatches(jobs=[]){return jobs.filter(j=>HOLD_IDS.some(k=>JSON.stringify(j).toLowerCase().includes(k.replace(/-/g,' ')))||HOLD_TITLES.some(t=>JSON.stringify(j).toLowerCase().includes(t.toLowerCase()))).map(j=>j.id)}
export function appendReportTimeline(root,event={}){ensureOperationalRecoveryRoots(root);fs.appendFileSync(reportTimelinePath(root),JSON.stringify({...event,timestamp:event.timestamp||new Date().toISOString()})+'\n')}
export function buildReportExecutionHealth(root,reportsStatus={},jobs=[]){const scheduledReports=EXPECTED_MORNING_JOBS.map(item=>{const match=(reportsStatus.recent||[]).find(r=>String(r.title||'').toLowerCase().includes(item.owner.toLowerCase())||String(r.reportType||'').toLowerCase().includes('digest'));const lastSuccessfulRun=match?.updatedAt||null;const stale=match?Boolean(match.stale):true;return{id:item.id,name:item.name,owner:item.owner,scheduleSource:item.scheduleSource,lastSuccessfulRun,lastFailedRun:null,currentlyRunning:jobs.some(j=>(j.owner||j.agent)===item.owner&&String(j.status).toLowerCase()==='running'&&item.taskPatterns.some(rx=>rx.test(`${j.task||''} ${j.title||''}`))),queued:jobs.some(j=>(j.owner||j.agent)===item.owner&&String(j.status).toLowerCase()==='queued'&&item.taskPatterns.some(rx=>rx.test(`${j.task||''} ${j.title||''}`))),stale,disabled:item.scheduleSource.startsWith('expected-'),degraded:stale||item.scheduleSource.startsWith('expected-')}});const stale=scheduledReports.filter(r=>r.stale);return{scheduledReports,lastSuccessfulRuns:scheduledReports.filter(r=>r.lastSuccessfulRun).map(r=>({id:r.id,at:r.lastSuccessfulRun})),lastFailedRuns:[],currentlyRunning:scheduledReports.filter(r=>r.currentlyRunning).map(r=>r.id),queued:scheduledReports.filter(r=>r.queued).map(r=>r.id),stale:stale.map(r=>r.id),disabled:scheduledReports.filter(r=>r.disabled).map(r=>r.id),degraded:scheduledReports.filter(r=>r.degraded).map(r=>r.id),schedulerHealth:stale.length?'DEGRADED':'LIVE',reportPipelineHealth:stale.length?'STALE':'LIVE',truthStatus:stale.length?'DEGRADED':'LIVE'}}
export function buildTaskOwnership(jobs=[]){return{activeTasks:jobs.filter(j=>!['completed','complete','cancelled','archived'].includes(String(j.status||'').toLowerCase())).slice(0,100).map(j=>({id:j.id,title:j.title||j.task,ownerAgent:j.owner||j.agent||'Unknown',executor:j.outputPayload?.executorProvider||j.routeStatus||'unassigned',status:j.status,evidenceLink:j.outputPayload?.evidencePath||null,localEligible:Boolean(j.inputPayload?.executionLane==='local_bridge'||String(j.routeStatus||'').includes('local_bridge')),localAttempted:Boolean(j.outputPayload?.localModelAttempted),gptUsed:Boolean(j.outputPayload?.gptUsed),approvalNeeded:Boolean(j.outputPayload?.patrickReviewNeeded||j.outputPayload?.perryReviewRequired)}))}}
export function buildStartupHealth({jobs=[],reportsStatus={}}={}){const schedulerRegistered=EXPECTED_MORNING_JOBS.length>0;const reportPipelinesRegistered=(reportsStatus.recent||[]).length>0;const timersActive=schedulerRegistered;const startupWarnings=[];if(!reportPipelinesRegistered)startupWarnings.push('No recent report artifacts indexed.');return{schedulerRegistered,workersRegistered:jobs.some(j=>String(j.status).toLowerCase()==='running'),reportPipelinesRegistered,timersActive,startupComplete:schedulerRegistered,startupWarnings,startupErrors:[],truthStatus:startupWarnings.length?'DEGRADED':'LIVE'}}
